### ISSUE TITLE
Question on GLU class

### ISSUE THREAD

**Issue by rustic-snob** [BobMcDear/attorch#5]
Thank you for your great work! I should have found out this repository earlier.

The thing I wanna ask is as of GLU function that you've implemented.

I noticed that xformer's implementation of SwiGLU(basically the same with GLU but fixed activation of SiLU) is fusing every kernel, not only the elem-wise multiplication of in-projected vector and gate-projected vector, but also projecting of those vectors and even output projection.

Is it computationally efficient to fusing only elem-wise multiplication? or is it your intention to make it more clear and hackable by separating those calculations?

I thought, besides output projection, fusing elem-wise multiplication and projecting in-projected vector and gate-projected vector would be efficient and kinda makes sense cuz I think, most of the time, GLU function works with those input projection and gate projection.

**Comment by BobMcDear** [comment]
Hello,

Thank you for your kind words! You are correct, GLU is typically sandwiched between the two linear layers of transformers' feedforward components (i.e., linear -> GLU -> linear), so it would be more efficient to fuse it with the linear layer preceding it. As you say, however, the objective of attorch is to provide simple, hackable blocks users can easily tweak, and efficiency is not its top priority. In general, please note that the kernels in this repository can be heavily optimized for LLM applications (e.g., linear layers and GLU, RMS norm and linear layers, linear layers and skip connections, etc.), but I did not want to center attorch around NLP, especially since there are already a number of excellent libraries dedicated to this domain, including xFormers and kernl. I might create a separate directory specifically for LLM modules in the future though.

**Comment by rustic-snob** [comment]
Thank you for your kind reply!
